FROM node:20-bullseye

RUN apt-get update \
  && apt-get install -y --no-install-recommends \
    ca-certificates \
    dpkg \
    fakeroot \
    git \
    python3 \
    python3-pip \
    rpm \
    xz-utils \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /repo

ENV npm_config_loglevel=warn

CMD ["bash"]
